# Generated by Django 3.1.1 on 2020-09-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200908_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='car_reg',
            field=models.CharField(blank=True, choices=[('SM16 SWF', 'SM16 SWF - Richards (White Toyota Hilux)'), ('FL64 EBN', 'FL64 EBN - Scotts (White Toyota Hilux)'), ('WG63 LVZ', 'WG63 LVZ - Volkswagen Caddy Van'), ('SC16 SYZ', 'SC16 SYZ - Vauxhall Movano Flatbed Truck'), ('SA13 KLJ', 'SA13 KLJ - Daniels (White Ford Ranger'), ('SJ62 RMU', 'SJ62 RMU - Matts (Black Toyota Hilux'), ('HG61 HGZ', 'HG61 HGZ - Tims (Blue Toyota Hilux)'), ('SC15 MYR', 'SC15 MYR - White Land Rover Defender'), ('XXXX ???', 'XXXX ??? - Alexs (Grey Toyota Hilux)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='contract_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
