# Generated by Django 3.1.1 on 2020-09-13 17:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200909_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertask',
            name='user',
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='usertask',
            name='all_tasks',
        ),
        migrations.AddField(
            model_name='usertask',
            name='all_tasks',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.task'),
            preserve_default=False,
        ),
    ]
