# Generated by Django 3.1.1 on 2020-09-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200918_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='day_of_the_week',
        ),
        migrations.AlterField(
            model_name='task',
            name='car_reg',
            field=models.CharField(blank=True, choices=[('SM16 SWF', 'SM16 SWF - White Toyota Hilux'), ('FL64 EBN', 'FL64 EBN - White Toyota Hilux'), ('WG63 LVZ', 'WG63 LVZ - Volkswagen Caddy Van'), ('SC16 SYZ', 'SC16 SYZ - Vauxhall Movano Flatbed Truck'), ('SA13 KLJ', 'SA13 KLJ - White Ford Ranger'), ('SJ62 RMU', 'SJ62 RMU - Black Toyota Hilux'), ('HG61 HGZ', 'HG61 HGZ - Blue Toyota Hilux'), ('SC15 MYR', 'SC15 MYR - White Land Rover Defender'), ('FG61 YVW', 'FG61 YVW - Grey Toyota Hilux')], max_length=20, null=True),
        ),
    ]
